from .login_form import LoginForm
from .signup_form import SignUpForm
from .edit_user_form import EditUserForm
from .create_film_form import CreateFilmForm
from .create_list_form import CreateListForm
from .edit_list_form import EditListForm
from .edit_film_form import EditFilmForm
from .create_review_form import CreateReviewForm
from .update_review_form import UpdateReviewForm
